package base

const (
	TypeAppHomeOpened         Type = "app_home_opened"
	TypeAppMention                 = "app_mention"
	TypeAppRequested               = "app_requested"
	TypeAppUninstalled             = "app_uninstalled"
	TypeCallRejected               = "call_rejected"
	TypeChannelArchive             = "channel_archive"
	TypeChannelCreated             = "channel_created"
	TypeChannelDeleted             = "channel_deleted"
	TypeChannelHistoryChanged      = "channel_history_changed"
	TypeChannelLeft                = "channel_left"
	TypeChannelShared              = "channel_shared"
	TypeChannelUnarchive           = "channel_unarchive"
	TypeChannelUnshared            = "channel_unshared"
	TypeDndUpdated                 = "dnd_updated"
	TypeDndUpdatedUser             = "dnd_updated_user"
	TypeEmailDomainChanged         = "email_domain_changed"
	TypeEmojiChanged               = "emoji_changed"
	TypeFileChange                 = "file_change"
	TypeFileCreated                = "file_created"
	TypeFileDeleted                = "file_deleted"
	TypeFilePublic                 = "file_public"
	TypeFileShared                 = "file_shared"
	TypeFileUnshared               = "file_unshared"
	TypeGridMigrationFinished      = "grid_migration_finished"
	TypeGridMigrationStarted       = "grid_migration_started"
	TypeGroupArchive               = "group_archive"
	TypeGroupClose                 = "group_close"
	TypeGroupDeleted               = "group_deleted"
	TypeGroupHistoryChanged        = "group_history_changed"
	TypeGroupLeft                  = "group_left"
	TypeGroupOpen                  = "group_open"
	TypeGroupRename                = "group_rename"
	TypeGroupUnarchive             = "group_unarchive"
	TypeIMClose                    = "im_close"
	TypeIMCreated                  = "im_created"
	TypeIMHistoryChanged           = "im_history_changed"
	TypeIMOpen                     = "im_open"
	TypeInviteRequested            = "invite_requested"
	TypeLinkShared                 = "link_shared"
	TypeMemberJoinedChannel        = "member_joined_channel"
	TypeMemberLeftChannel          = "member_left_channel"
	TypeMessage                    = "message"
	TypePinAdded                   = "pin_added"
	TypePinRemoved                 = "pin_removed"
	TypeReactionAdded              = "reaction_added"
	TypeReactionRemoved            = "reaction_removed"
	TypeStarAdded                  = "star_added"
	TypeStarRemoved                = "star_removed"
	TypeSubteamCreated             = "subteam_created"
	TypeSubteamMembersChanged      = "subteam_members_changed"
	TypeSubteamSelfAdded           = "subteam_self_added"
	TypeSubteamSelfRemoved         = "subteam_self_removed"
	TypeSubteamUpdated             = "subteam_updated"
	TypeTeamDomainChange           = "team_domain_change"
	TypeTeamJoin                   = "team_join"
	TypeTeamRename                 = "team_rename"
	TypeTokensRevoked              = "tokens_revoked"
)

type Type string
